name: "Setup Python Environment"
description: "Set up Python environment for the given Python version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.12"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.6.14"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"
  pnpm-version:
    description: "pnpm version to use"
    required: false
    default: "8"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: {% raw %}${{ inputs.uv-version }}{% endraw %}
        enable-cache: 'true'
        cache-suffix: {% raw %}${{ matrix.python-version }}{% endraw %}

    - name: Install Python dependencies
      run: uv sync --frozen
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: {% raw %}${{ inputs.node-version }}{% endraw %}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: {% raw %}${{ inputs.pnpm-version }}{% endraw %}

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash
